# Generated by Django 4.2.20 on 2025-03-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_specialoffer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='text',
            field=models.TextField(max_length=40),
        ),
    ]
