# Generated by Django 4.2.20 on 2025-05-25 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_imagetheme_remove_ordermodel_digital_products_and_more'),
        ('home', '0003_alter_specialoffer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='buy_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity to buy to trigger offer (used for Buy X Get Y).', null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='discount_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='Percentage discount to apply (used with theme-based offers).', null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='get_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity to get free (used for Buy X Get Y).', null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum amount required for offer to apply (used for free shipping).', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='offer_type',
            field=models.CharField(blank=True, choices=[('free_shipping', 'Free Shipping Over Amount'), ('percentage_discount', 'Percentage Discount on Theme'), ('buy_x_get_y', 'Buy X Get Y Free')], help_text='Type of offer being applied.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='Theme the discount applies to (used with percentage discounts).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.imagetheme'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='expiry_date',
            field=models.DateTimeField(help_text='Datetime when the offer becomes inactive.'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='text',
            field=models.TextField(help_text='Short description of the offer.', max_length=100),
        ),
    ]
