# Generated by Django 4.2.20 on 2025-05-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_specialoffer_buy_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='offer_type',
            field=models.CharField(choices=[('free_shipping', 'Free Shipping Over Amount'), ('percentage_discount', 'Percentage Discount on Theme'), ('buy_x_get_y', 'Buy X Get Y Free')], default='free_shipping', help_text='Type of offer being applied.', max_length=30),
            preserve_default=False,
        ),
    ]
