# Generated by Django 4.2.20 on 2025-03-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name_plural': 'Order History'},
        ),
    ]
