# Generated by Django 4.2.20 on 2025-05-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_imagetheme_remove_ordermodel_digital_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy'), ('terms', 'Terms & Conditions')], max_length=50, unique=True)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
