# Generated by Django 4.2.20 on 2025-09-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_policypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
