# Generated by Django 4.2.20 on 2025-03-19 00:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('theme', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('digital', 'Digital Download'), ('printed', 'Printed Product')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('license_type', models.CharField(blank=True, choices=[('personal', 'Personal License'), ('commercial', 'Commercial License'), ('advertising', 'Advertising License')], max_length=20, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_preview', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image_preview')),
                ('image_framed', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image_framed')),
                ('image_canvas', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image_canvas')),
                ('image_room_mockup', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image_room_mockup')),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file')),
                ('print_type', models.CharField(blank=True, choices=[('canvas', 'Canvas Wrap'), ('framed', 'Framed Print'), ('mug', 'Mug'), ('poster', 'Poster Print')], max_length=20, null=True)),
                ('size', models.CharField(blank=True, default='Standard', max_length=50, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, default=10, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='products.tag')),
            ],
        ),
    ]
