# Generated by Django 4.2.20 on 2025-03-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_licensetype_is_active_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='print_types',
            field=models.ManyToManyField(blank=True, to='products.printtype'),
        ),
    ]
