# Generated by Django 4.2.20 on 2025-03-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_print_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Ireland', max_length=100)),
                ('flat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
