# Generated by Django 4.2.20 on 2025-03-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_countryvat_shipper_shippingrate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='tracking_url',
            field=models.URLField(blank=True, help_text='URL to the tracking page (use {tracking_number} as a placeholder)', max_length=500),
        ),
    ]
