# Generated by Django 4.2.20 on 2025-03-29 19:29

from django.db import migrations


def link_printtypes(apps, schema_editor):
    PrintType = apps.get_model('products', 'PrintType')
    ProductType = apps.get_model('products', 'ProductType')

    mapping = {
        "Poster Print": "Poster",
        "Canvas Wrap": "Canvas",
        "Framed Print": "Framed",
        "Mug": "Mug",
    }

    for print_name, product_type_name in mapping.items():
        try:
            pt = ProductType.objects.get(name=product_type_name)
            print_type = PrintType.objects.get(name=print_name)
            print_type.product_type = pt
            print_type.save()
        except ProductType.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_printtype_product_type'),
    ]

    operations = [
        migrations.RunPython(link_printtypes),
    ]
