# Generated by Django 4.2.20 on 2025-03-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20250329_1929'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingrate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='shipping_option',
            field=models.CharField(choices=[('standard', 'Standard'), ('courier', 'Courier')], default='standard', help_text='User-selectable shipping option (e.g. standard, courier)', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='shippingrate',
            unique_together={('product_type', 'shipping_option', 'shipper', 'country')},
        ),
    ]
